"use client";

import Link from "next/link";
import { useState } from "react";

type Lang="en"|"bn"|"hi";
const copy={
  en:{tag:"VERIFIED PROVIDER PROGRAM",title:"Build trust. Earn professionally.",desc:"CreatorFix only allows verified specialists to offer services. NID and live face verification are mandatory, followed by a BDT 1,000 refundable security deposit and manual admin review.",cta:"Create Account & Start",journey:"Your provider journey",s1:"Create and verify your CreatorFix account.",s2:"Upload NID front, NID back and complete live face capture.",s3:"Keep BDT 1,000 as a refundable security deposit while your provider account is active.",s4:"Add your professional bio and skills, then wait for admin approval."},
  bn:{tag:"ভেরিফায়েড প্রোভাইডার প্রোগ্রাম",title:"বিশ্বাস তৈরি করুন। প্রফেশনালি আয় করুন।",desc:"CreatorFix-এ শুধুমাত্র যাচাইকৃত বিশেষজ্ঞরা সার্ভিস দিতে পারবেন। NID ও লাইভ ফেস ভেরিফিকেশন বাধ্যতামূলক। এরপর প্রোভাইডার অ্যাকাউন্ট সক্রিয় রাখতে ১,০০০ টাকা ফেরতযোগ্য সিকিউরিটি ডিপোজিট এবং অ্যাডমিন রিভিউ লাগবে।",cta:"অ্যাকাউন্ট খুলে শুরু করুন",journey:"আপনার প্রোভাইডার জার্নি",s1:"CreatorFix অ্যাকাউন্ট তৈরি ও ভেরিফাই করুন।",s2:"NID-এর সামনে, পেছন এবং লাইভ ফেস ক্যাপচার দিন।",s3:"প্রোভাইডার অ্যাকাউন্ট সক্রিয় থাকা পর্যন্ত ১,০০০ টাকা ফেরতযোগ্য সিকিউরিটি ডিপোজিট হিসেবে রাখুন।",s4:"অভিজ্ঞতা ও দক্ষতা যোগ করে অ্যাডমিন অনুমোদনের জন্য অপেক্ষা করুন।"},
  hi:{tag:"वेरिफाइड प्रोवाइडर प्रोग्राम",title:"विश्वास बनाइए। प्रोफेशनली कमाइए।",desc:"CreatorFix पर केवल सत्यापित विशेषज्ञ ही सेवाएं दे सकते हैं। NID और लाइव फेस वेरिफिकेशन अनिवार्य है। इसके बाद सक्रिय प्रोवाइडर अकाउंट के लिए BDT 1,000 रिफंडेबल सिक्योरिटी डिपॉजिट और एडमिन रिव्यू आवश्यक है।",cta:"अकाउंट बनाकर शुरू करें",journey:"आपकी प्रोवाइडर यात्रा",s1:"अपना CreatorFix अकाउंट बनाएं और सत्यापित करें।",s2:"NID फ्रंट, NID बैक और लाइव फेस कैप्चर पूरा करें।",s3:"प्रोवाइडर अकाउंट सक्रिय रहने तक BDT 1,000 रिफंडेबल सिक्योरिटी डिपॉजिट रखें।",s4:"अपनी प्रोफेशनल जानकारी और कौशल जोड़ें, फिर एडमिन अनुमोदन का इंतजार करें।"}
};

export default function ProviderRegister() {
  const [lang,setLang]=useState<Lang>("en"); const t=copy[lang];
  return <main className="provider-onboarding"><style>{`
    .provider-onboarding{min-height:100vh;background:radial-gradient(circle at 85% 10%,#183e70 0,transparent 30%),radial-gradient(circle at 10% 90%,#3a1b5d 0,transparent 35%),#07111f;color:#fff;padding:28px 20px}.provider-shell{max-width:980px;margin:auto}.provider-top{display:flex;justify-content:space-between;align-items:center;gap:16px}.langs{display:flex;gap:7px;flex-wrap:wrap}.lang{background:#14233a;color:#fff;border:1px solid #38587e;border-radius:10px;padding:9px 12px;cursor:pointer}.lang.active{background:#438cff}.provider-hero{margin-top:55px;display:grid;grid-template-columns:1.1fr .9fr;gap:32px;align-items:start}.provider-card{border:1px solid #294564;background:#0d1929cc;border-radius:22px;padding:24px}.steps{display:grid;gap:12px}.step{padding:18px;border-radius:14px;background:#101f33;border:1px solid #253f5d}.step strong{display:block;color:#77adff;margin-bottom:5px}.cta{display:inline-block;margin-top:22px;padding:15px 20px;border-radius:12px;background:linear-gradient(135deg,#438cff,#7658ff);font-weight:800}.note{color:#9fb1c7;line-height:1.7}@media(max-width:760px){.provider-hero{grid-template-columns:1fr}}`}</style>
    <div className="provider-shell"><div className="provider-top"><Link href="/">← CreatorFix</Link><div className="langs">{([["en","English"],["bn","বাংলা"],["hi","हिंदी"]] as const).map(([id,label])=><button key={id} className={"lang "+(lang===id?"active":"")} onClick={()=>setLang(id)}>{label}</button>)}</div></div>
    <section className="provider-hero"><div><span style={{color:"#8ab8ff",fontWeight:800}}>{t.tag}</span><h1 style={{fontSize:"clamp(42px,8vw,76px)",lineHeight:1,margin:"18px 0"}}>{t.title}</h1><p className="note">{t.desc}</p><Link className="cta" href="/register">{t.cta} →</Link></div>
    <div className="provider-card"><h2 style={{marginTop:0}}>{t.journey}</h2><div className="steps"><div className="step"><strong>01 — Account</strong>{t.s1}</div><div className="step"><strong>02 — Identity</strong>{t.s2}</div><div className="step"><strong>03 — Security Deposit</strong>{t.s3}</div><div className="step"><strong>04 — Admin Review</strong>{t.s4}</div></div></div></section></div>
  </main>;
}