"use server";
import { z } from "zod";
import { requireRole } from "@/lib/auth/require-role";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
const money=z.coerce.number().finite().positive().max(1000000), id=z.string().uuid();
const p=(v:number)=>Math.round(v*100);
export async function submitDepositAction(input:{amount:number;paymentMethod:string;paymentReference:string}){try{const me=await requireRole(["customer","provider","admin"]);const a=money.safeParse(input.amount);if(!a.success)return{ok:false,error:"Enter a valid deposit amount."};const method=String(input.paymentMethod||"").trim().slice(0,80),ref=String(input.paymentReference||"").trim().slice(0,160);if(!method||!ref)return{ok:false,error:"Payment method and transaction reference are required."};const db=createAdminSupabaseClient();const{error}=await db.from("deposits").insert({user_id:me.id,amount:p(a.data),payment_method:method,payment_reference:ref,status:"pending"});return error?{ok:false,error:error.message}:{ok:true}}catch{return{ok:false,error:"Unable to submit deposit request."}}}
export async function requestWalletWithdrawalAction(input:{amount:number;payoutMethod:string;payoutAccount:string}){try{const me=await requireRole(["customer","provider","admin"]);const a=money.safeParse(input.amount);if(!a.success)return{ok:false,error:"Enter a valid withdrawal amount."};const method=String(input.payoutMethod||"").trim().slice(0,80),account=String(input.payoutAccount||"").trim().slice(0,180);if(!method||!account)return{ok:false,error:"Payout method and account details are required."};const{error}=await createAdminSupabaseClient().rpc("submit_wallet_withdrawal_request",{p_user_id:me.id,p_amount:p(a.data),p_payout_method:method,p_payout_account:account});return error?{ok:false,error:error.message.includes("INSUFFICIENT")?"Insufficient available balance.":error.message}:{ok:true}}catch{return{ok:false,error:"Unable to request withdrawal."}}}
export async function adminApproveDepositAction(depositId:string){const d=id.safeParse(depositId);if(!d.success)return{ok:false,error:"Invalid deposit."};const actor=await requireRole(["admin"]),db=createAdminSupabaseClient();const{data:dep,error:re}=await db.from("deposits").select("id,user_id,amount,status").eq("id",d.data).single();if(re||!dep)return{ok:false,error:"Deposit not found."};if(dep.status!=="pending")return{ok:false,error:"Deposit already reviewed."};const{data:w,error:we}=await db.from("wallets").select("id").eq("user_id",dep.user_id).single();if(we||!w)return{ok:false,error:"Wallet not found."};const{error:te}=await db.rpc("apply_wallet_transaction",{p_wallet_id:w.id,p_type:"deposit",p_amount:dep.amount,p_reference_type:"deposit",p_reference_id:dep.id,p_idempotency_key:"deposit-approved:"+dep.id,p_actor:actor.id});if(te)return{ok:false,error:te.message};const{error}=await db.from("deposits").update({status:"verified",reviewed_by:actor.id,reviewed_at:new Date().toISOString()}).eq("id",dep.id);if(error)return{ok:false,error:error.message};await db.from("audit_logs").insert({actor_id:actor.id,action:"deposit_approved",entity_type:"deposit",entity_id:dep.id,after_state:{amount:dep.amount,user_id:dep.user_id}});return{ok:true}}
export async function adminRejectDepositAction(depositId:string){const d=id.safeParse(depositId);if(!d.success)return{ok:false,error:"Invalid deposit."};const actor=await requireRole(["admin"]),db=createAdminSupabaseClient();const{error}=await db.from("deposits").update({status:"rejected",reviewed_by:actor.id,reviewed_at:new Date().toISOString()}).eq("id",d.data).eq("status","pending");return error?{ok:false,error:error.message}:{ok:true}}
export async function adminReviewWalletWithdrawalAction(requestId:string,action:"paid"|"rejected",reason?:string){const d=id.safeParse(requestId);if(!d.success)return{ok:false,error:"Invalid withdrawal."};const actor=await requireRole(["admin"]),db=createAdminSupabaseClient();const{error}=await db.rpc("review_wallet_withdrawal_request",{p_request_id:d.data,p_action:action,p_admin_id:actor.id,p_reason:reason||null});return error?{ok:false,error:error.message}:{ok:true}}
export async function adminAdjustWalletAction(userId:string,amount:number,note:string){const uid=id.safeParse(userId),a=z.coerce.number().finite().refine(v=>v!==0&&Math.abs(v)<=1000000).safeParse(amount);if(!uid.success||!a.success)return{ok:false,error:"Invalid adjustment."};const actor=await requireRole(["admin"]),db=createAdminSupabaseClient();const{data:w,error:we}=await db.from("wallets").select("id").eq("user_id",uid.data).single();if(we||!w)return{ok:false,error:"Wallet not found."};const ref=crypto.randomUUID();const{error}=await db.rpc("apply_wallet_transaction",{p_wallet_id:w.id,p_type:"adjustment",p_amount:p(a.data),p_reference_type:(note||"admin_adjustment").slice(0,120),p_reference_id:ref,p_idempotency_key:"admin-adjustment:"+ref,p_actor:actor.id});if(error)return{ok:false,error:error.message};await db.from("audit_logs").insert({actor_id:actor.id,action:"wallet_adjusted",entity_type:"profile",entity_id:uid.data,after_state:{amount:p(a.data),note}});return{ok:true}}
export async function adminSetAccountStatusAction(userId:string,status:"active"|"suspended"|"banned"|"pending"){const uid=id.safeParse(userId);if(!uid.success)return{ok:false,error:"Invalid user."};const actor=await requireRole(["admin"]),db=createAdminSupabaseClient();const{error}=await db.from("profiles").update({status}).eq("id",uid.data);if(error)return{ok:false,error:error.message};await db.from("audit_logs").insert({actor_id:actor.id,action:"account_status_changed",entity_type:"profile",entity_id:uid.data,after_state:{status}});return{ok:true}}